### ISSUE TITLE
Model.__setattr__ unconditionally marks Fields as dirty

### ISSUE THREAD

**Issue by natecode** [mathcamp/flywheel#26]
The `flywheel/models.py` code for Model calls `self.mark_dirty_()` for every field that the user assigns to. However, it's possible the values before/after are identical, wasting a round trip to DynamoDB and write capacity.

Would you consider checking the value and if the assignment would have no effect, skipping it? I'm ok if the check is only shallow and doesn't cover nested structures (dict within dict etc.), although that might be nice too. Thanks!

**Comment by stevearc** [comment]
I'm looking into it. Trying to decide what the best behavior is for mutable fields, but the behavior can definitely be made better.
