### ISSUE TITLE
Add support for engine.connect()

### ISSUE THREAD

**Issue by mapleoin** [mathcamp/flywheel#30]
It would be good to have support for dynamo3's connect method instead of having two separate methods connecting: `connect_to_host` and `connect_to_region`.

Also, `dynamo3` seems to have deprecated the `connect_to_host` and `connect_to_region` methods in the version which is used by the latest flywheel release. So there are DeprecationWarnings everywhere.

**Comment by stevearc** [comment]
Yessss...I should do something about that. Ideally I really want to switch over to using boto3 now that it's out and supports python 3, but that's such a large project I haven't made much headway. I'll think about doing a smaller point release with this and maybe a couple other small fixes and cleanups.

**Comment by mapleoin** [comment]
This seems to have been fixed (by accident? the commit message doesn't mention it) in https://github.com/mathcamp/flywheel/commit/38c3866e67a5e38e6d8cd85f35a7669abae00fdc and released in 0.4.5.

Thanks!

**Comment by stevearc** [comment]
Yep, I just forgot to circle back to this issue. Thanks for picking it up for me!
