### ISSUE TITLE
Model.save() missing?

### ISSUE THREAD

**Issue by Christoph-Schabert** [mathcamp/flywheel#40]
In the [documentation](http://flywheel.readthedocs.org/en/latest/topics/crud.html#save) is explained that every model has a .save method.

But in the source code this method is missing.
https://github.com/mathcamp/flywheel/blob/0.4.8/flywheel/models.py#L138-L158

is this a bug?

**Comment by stevearc** [comment]
Huh...would you look at that? Those docs are so thorough they cover features that don't even exist yet!

Yeah that's a bug. Probably no one's noticed yet because you usually want to do a sync instead of a save after the model has already been persisted. I'll get a fix in.

**Comment by Christoph-Schabert** [comment]
Thank you!
This was exactly that what i looking for
