### ISSUE TITLE
What is the best way to update just one model attribute

### ISSUE THREAD

**Issue by Govinda-Fichtner** [mathcamp/flywheel#43]
Sync seems to update all changed attributes of a model.

Is there a way to update just one attribute (for instance for status updates)? 

Similar to ActiveRecord's [update_column](http://apidock.com/rails/v3.1.0/ActiveRecord/Persistence/update_column).

**Comment by stevearc** [comment]
There's no mechanism for doing that at the moment, but it doesn't seem too involved to add. I'll look into it.

**Comment by stevearc** [comment]
Added the [update_field](https://github.com/mathcamp/flywheel/blob/0.4.9/flywheel/engine.py#L642) method to the Engine and released in version [0.4.9](https://pypi.python.org/pypi/flywheel/0.4.9)

**Comment by Govinda-Fichtner** [comment]
@stevearc Awesome that this happened so fast. Really like this for updating my status fields in my models!
